name: sql_serializable
description: A code generator & runtime library for converting Dart classes to/from SQL.
version: 0.1.0-dev.0
repository: https://github.com/abitofevrything/sql_serializable

environment:
  sdk: '>=3.0.0-151.0.dev <4.0.0'

dependencies: 
  analyzer: ^5.4.0
  build: ^2.3.1
  collection: ^1.17.1 
  grammer: ^1.0.3
  meta: ^1.8.0
  source_gen: ^1.2.6
  source_helper: ^1.3.3

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
